---
collections:
  - name: oracle.oci
    version: "5.5.0"

  - name: ansible.posix
    version: "1.5.4"

  - name: community.general
    version: "8.0.0"

  - name: ansible.builtin
    version: ">=2.16.0"
